<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([
            ['cod' => 1, 'des' => 'EL ENCANTO', 'coddep' => '1'],
            ['cod' => 2, 'des' => 'LA CHORRERA', 'coddep' => '1'],
            ['cod' => 3, 'des' => 'LA PEDRERA', 'coddep' => '1'],
            ['cod' => 4, 'des' => 'LA VICTORIA', 'coddep' => '1'],
            ['cod' => 5, 'des' => 'LETICIA', 'coddep' => '1'],
            ['cod' => 6, 'des' => 'MIRITI - PARANA', 'coddep' => '1'],
            ['cod' => 7, 'des' => 'PUERTO ALEGRIA', 'coddep' => '1'],
            ['cod' => 8, 'des' => 'PUERTO ARICA', 'coddep' => '1'],
            ['cod' => 9, 'des' => 'PUERTO NARIÑO', 'coddep' => '1'],
            ['cod' => 10, 'des' => 'PUERTO SANTANDER', 'coddep' => '1'],
            ['cod' => 11, 'des' => 'TARAPACA', 'coddep' => '1'],
            ['cod' => 12, 'des' => 'ABEJORRAL', 'coddep' => '2'],
            ['cod' => 13, 'des' => 'ABRIAQUI', 'coddep' => '2'],
            ['cod' => 14, 'des' => 'ALEJANDRIA', 'coddep' => '2'],
            ['cod' => 15, 'des' => 'AMAGA', 'coddep' => '2'],
            ['cod' => 16, 'des' => 'AMALFI', 'coddep' => '2'],
            ['cod' => 17, 'des' => 'ANDES', 'coddep' => '2'],
            ['cod' => 18, 'des' => 'ANGELOPOLIS', 'coddep' => '2'],
            ['cod' => 19, 'des' => 'ANGOSTURA', 'coddep' => '2'],
            ['cod' => 20, 'des' => 'ANORI', 'coddep' => '2'],
            ['cod' => 21, 'des' => 'ANZA', 'coddep' => '2'],
            ['cod' => 22, 'des' => 'APARTADO', 'coddep' => '2'],
            ['cod' => 23, 'des' => 'ARBOLETES', 'coddep' => '2'],
            ['cod' => 24, 'des' => 'ARGELIA', 'coddep' => '2'],
            ['cod' => 25, 'des' => 'ARMENIA', 'coddep' => '2'],
            ['cod' => 26, 'des' => 'BARBOSA', 'coddep' => '2'],
            ['cod' => 27, 'des' => 'BELLO', 'coddep' => '2'],
            ['cod' => 28, 'des' => 'BELMIRA', 'coddep' => '2'],
            ['cod' => 29, 'des' => 'BETANIA', 'coddep' => '2'],
            ['cod' => 30, 'des' => 'BETULIA', 'coddep' => '2'],
            ['cod' => 31, 'des' => 'BRICEÑO', 'coddep' => '2'],
            ['cod' => 32, 'des' => 'BURITICA', 'coddep' => '2'],
            ['cod' => 33, 'des' => 'CACERES', 'coddep' => '2'],
            ['cod' => 34, 'des' => 'CAICEDO', 'coddep' => '2'],
            ['cod' => 35, 'des' => 'CALDAS', 'coddep' => '2'],
            ['cod' => 36, 'des' => 'CAMPAMENTO', 'coddep' => '2'],
            ['cod' => 37, 'des' => 'CAÑASGORDAS', 'coddep' => '2'],
            ['cod' => 38, 'des' => 'CARACOLI', 'coddep' => '2'],
            ['cod' => 39, 'des' => 'CARAMANTA', 'coddep' => '2'],
            ['cod' => 40, 'des' => 'CAREPA', 'coddep' => '2'],
            ['cod' => 41, 'des' => 'CAROLINA', 'coddep' => '2'],
            ['cod' => 42, 'des' => 'CAUCASIA', 'coddep' => '2'],
            ['cod' => 43, 'des' => 'CHIGORODO', 'coddep' => '2'],
            ['cod' => 44, 'des' => 'CISNEROS', 'coddep' => '2'],
            ['cod' => 45, 'des' => 'CIUDAD BOLIVAR', 'coddep' => '2'],
            ['cod' => 46, 'des' => 'COCORNA', 'coddep' => '2'],
            ['cod' => 47, 'des' => 'CONCEPCION', 'coddep' => '2'],
            ['cod' => 48, 'des' => 'CONCORDIA', 'coddep' => '2'],
            ['cod' => 49, 'des' => 'COPACABANA', 'coddep' => '2'],
            ['cod' => 50, 'des' => 'DABEIBA', 'coddep' => '2'],
            ['cod' => 51, 'des' => 'DONMATIAS', 'coddep' => '2'],
            ['cod' => 52, 'des' => 'EBEJICO', 'coddep' => '2'],
            ['cod' => 53, 'des' => 'EL BAGRE', 'coddep' => '2'],
            ['cod' => 54, 'des' => 'EL CARMEN DE VIBORAL', 'coddep' => '2'],
            ['cod' => 55, 'des' => 'EL SANTUARIO', 'coddep' => '2'],
            ['cod' => 56, 'des' => 'ENTRERRIOS', 'coddep' => '2'],
            ['cod' => 57, 'des' => 'ENVIGADO', 'coddep' => '2'],
            ['cod' => 58, 'des' => 'FREDONIA', 'coddep' => '2'],
            ['cod' => 59, 'des' => 'FRONTINO', 'coddep' => '2'],
            ['cod' => 60, 'des' => 'GIRALDO', 'coddep' => '2'],
            ['cod' => 61, 'des' => 'GIRARDOTA', 'coddep' => '2'],
            ['cod' => 62, 'des' => 'GOMEZ PLATA', 'coddep' => '2'],
            ['cod' => 63, 'des' => 'GRANADA', 'coddep' => '2'],
            ['cod' => 64, 'des' => 'GUADALUPE', 'coddep' => '2'],
            ['cod' => 65, 'des' => 'GUARNE', 'coddep' => '2'],
            ['cod' => 66, 'des' => 'GUATAPE', 'coddep' => '2'],
            ['cod' => 67, 'des' => 'HELICONIA', 'coddep' => '2'],
            ['cod' => 68, 'des' => 'HISPANIA', 'coddep' => '2'],
            ['cod' => 69, 'des' => 'ITAGUI', 'coddep' => '2'],
            ['cod' => 70, 'des' => 'ITUANGO', 'coddep' => '2'],
            ['cod' => 71, 'des' => 'JARDIN', 'coddep' => '2'],
            ['cod' => 72, 'des' => 'JERICO', 'coddep' => '2'],
            ['cod' => 73, 'des' => 'LA CEJA', 'coddep' => '2'],
            ['cod' => 74, 'des' => 'LA ESTRELLA', 'coddep' => '2'],
            ['cod' => 75, 'des' => 'LA PINTADA', 'coddep' => '2'],
            ['cod' => 76, 'des' => 'LA UNION', 'coddep' => '2'],
            ['cod' => 77, 'des' => 'LIBORINA', 'coddep' => '2'],
            ['cod' => 78, 'des' => 'MACEO', 'coddep' => '2'],
            ['cod' => 79, 'des' => 'MARINILLA', 'coddep' => '2'],
            ['cod' => 80, 'des' => 'MEDELLIN', 'coddep' => '2'],
            ['cod' => 81, 'des' => 'MONTEBELLO', 'coddep' => '2'],
            ['cod' => 82, 'des' => 'MURINDO', 'coddep' => '2'],
            ['cod' => 83, 'des' => 'MUTATA', 'coddep' => '2'],
            ['cod' => 84, 'des' => 'NARIÑO', 'coddep' => '2'],
            ['cod' => 85, 'des' => 'NECHI', 'coddep' => '2'],
            ['cod' => 86, 'des' => 'NECOCLI', 'coddep' => '2'],
            ['cod' => 87, 'des' => 'OLAYA', 'coddep' => '2'],
            ['cod' => 88, 'des' => 'PEÑOL', 'coddep' => '2'],
            ['cod' => 89, 'des' => 'PEQUE', 'coddep' => '2'],
            ['cod' => 90, 'des' => 'PUEBLORRICO', 'coddep' => '2'],
            ['cod' => 91, 'des' => 'PUERTO BERRIO', 'coddep' => '2'],
            ['cod' => 92, 'des' => 'PUERTO NARE', 'coddep' => '2'],
            ['cod' => 93, 'des' => 'PUERTO TRIUNFO', 'coddep' => '2'],
            ['cod' => 94, 'des' => 'REMEDIOS', 'coddep' => '2'],
            ['cod' => 95, 'des' => 'RETIRO', 'coddep' => '2'],
            ['cod' => 96, 'des' => 'RIONEGRO', 'coddep' => '2'],
            ['cod' => 97, 'des' => 'SABANALARGA', 'coddep' => '2'],
            ['cod' => 98, 'des' => 'SABANETA', 'coddep' => '2'],
            ['cod' => 99, 'des' => 'SALGAR', 'coddep' => '2'],
            ['cod' => 100, 'des' => 'SAN ANDRES DE CUERQUIA', 'coddep' => '2'],
            ['cod' => 101, 'des' => 'SAN CARLOS', 'coddep' => '2'],
            ['cod' => 102, 'des' => 'SAN FRANCISCO', 'coddep' => '2'],
            ['cod' => 103, 'des' => 'SAN JERONIMO', 'coddep' => '2'],
            ['cod' => 104, 'des' => 'SAN JOSE DE LA MONTAÑA', 'coddep' => '2'],
            ['cod' => 105, 'des' => 'SAN JUAN DE URABA', 'coddep' => '2'],
            ['cod' => 106, 'des' => 'SAN LUIS', 'coddep' => '2'],
            ['cod' => 107, 'des' => 'SAN PEDRO DE LOS MILAGROS', 'coddep' => '2'],
            ['cod' => 108, 'des' => 'SAN PEDRO DE URABA', 'coddep' => '2'],
            ['cod' => 109, 'des' => 'SAN RAFAEL', 'coddep' => '2'],
            ['cod' => 110, 'des' => 'SAN ROQUE', 'coddep' => '2'],
            ['cod' => 111, 'des' => 'SAN VICENTE', 'coddep' => '2'],
            ['cod' => 112, 'des' => 'SANTA BARBARA', 'coddep' => '2'],
            ['cod' => 113, 'des' => 'SANTA ROSA DE OSOS', 'coddep' => '2'],
            ['cod' => 114, 'des' => 'SANTAFE DE ANTIOQUIA', 'coddep' => '2'],
            ['cod' => 115, 'des' => 'SANTO DOMINGO', 'coddep' => '2'],
            ['cod' => 116, 'des' => 'SEGOVIA', 'coddep' => '2'],
            ['cod' => 117, 'des' => 'SONSON', 'coddep' => '2'],
            ['cod' => 118, 'des' => 'SOPETRAN', 'coddep' => '2'],
            ['cod' => 119, 'des' => 'TAMESIS', 'coddep' => '2'],
            ['cod' => 120, 'des' => 'TARAZA', 'coddep' => '2'],
            ['cod' => 121, 'des' => 'TARSO', 'coddep' => '2'],
            ['cod' => 122, 'des' => 'TITIRIBI', 'coddep' => '2'],
            ['cod' => 123, 'des' => 'TOLEDO', 'coddep' => '2'],
            ['cod' => 124, 'des' => 'TURBO', 'coddep' => '2'],
            ['cod' => 125, 'des' => 'URAMITA', 'coddep' => '2'],
            ['cod' => 126, 'des' => 'URRAO', 'coddep' => '2'],
            ['cod' => 127, 'des' => 'VALDIVIA', 'coddep' => '2'],
            ['cod' => 128, 'des' => 'VALPARAISO', 'coddep' => '2'],
            ['cod' => 129, 'des' => 'VEGACHI', 'coddep' => '2'],
            ['cod' => 130, 'des' => 'VENECIA', 'coddep' => '2'],
            ['cod' => 131, 'des' => 'VIGIA DEL FUERTE', 'coddep' => '2'],
            ['cod' => 132, 'des' => 'YALI', 'coddep' => '2'],
            ['cod' => 133, 'des' => 'YARUMAL', 'coddep' => '2'],
            ['cod' => 134, 'des' => 'YOLOMBO', 'coddep' => '2'],
            ['cod' => 135, 'des' => 'YONDO', 'coddep' => '2'],
            ['cod' => 136, 'des' => 'ZARAGOZA', 'coddep' => '2'],
            ['cod' => 137, 'des' => 'ARAUCA', 'coddep' => '3'],
            ['cod' => 138, 'des' => 'ARAUQUITA', 'coddep' => '3'],
            ['cod' => 139, 'des' => 'CRAVO NORTE', 'coddep' => '3'],
            ['cod' => 140, 'des' => 'FORTUL', 'coddep' => '3'],
            ['cod' => 141, 'des' => 'PUERTO RONDON', 'coddep' => '3'],
            ['cod' => 142, 'des' => 'SARAVENA', 'coddep' => '3'],
            ['cod' => 143, 'des' => 'TAME', 'coddep' => '3'],
            ['cod' => 144, 'des' => 'BARANOA', 'coddep' => '4'],
            ['cod' => 145, 'des' => 'BARRANQUILLA', 'coddep' => '4'],
            ['cod' => 146, 'des' => 'CAMPO DE LA CRUZ', 'coddep' => '4'],
            ['cod' => 147, 'des' => 'CANDELARIA', 'coddep' => '4'],
            ['cod' => 148, 'des' => 'GALAPA', 'coddep' => '4'],
            ['cod' => 149, 'des' => 'JUAN DE ACOSTA', 'coddep' => '4'],
            ['cod' => 150, 'des' => 'LURUACO', 'coddep' => '4'],
            ['cod' => 151, 'des' => 'MALAMBO', 'coddep' => '4'],
            ['cod' => 152, 'des' => 'MANATI', 'coddep' => '4'],
            ['cod' => 153, 'des' => 'PALMAR DE VARELA', 'coddep' => '4'],
            ['cod' => 154, 'des' => 'PIOJO', 'coddep' => '4'],
            ['cod' => 155, 'des' => 'POLONUEVO', 'coddep' => '4'],
            ['cod' => 156, 'des' => 'PONEDERA', 'coddep' => '4'],
            ['cod' => 157, 'des' => 'PUERTO COLOMBIA', 'coddep' => '4'],
            ['cod' => 158, 'des' => 'REPELON', 'coddep' => '4'],
            ['cod' => 159, 'des' => 'SABANAGRANDE', 'coddep' => '4'],
            ['cod' => 160, 'des' => 'SABANALARGA', 'coddep' => '4'],
            ['cod' => 161, 'des' => 'SANTA LUCIA', 'coddep' => '4'],
            ['cod' => 162, 'des' => 'SANTO TOMAS', 'coddep' => '4'],
            ['cod' => 163, 'des' => 'SOLEDAD', 'coddep' => '4'],
            ['cod' => 164, 'des' => 'SUAN', 'coddep' => '4'],
            ['cod' => 165, 'des' => 'TUBARA', 'coddep' => '4'],
            ['cod' => 166, 'des' => 'USIACURI', 'coddep' => '4'],
            ['cod' => 167, 'des' => 'BOGOTA', 'coddep' => '5'],
            ['cod' => 168, 'des' => 'ACHI', 'coddep' => '6'],
            ['cod' => 169, 'des' => 'ALTOS DEL ROSARIO', 'coddep' => '6'],
            ['cod' => 170, 'des' => 'ARENAL', 'coddep' => '6'],
            ['cod' => 171, 'des' => 'ARJONA', 'coddep' => '6'],
            ['cod' => 172, 'des' => 'ARROYOHONDO', 'coddep' => '6'],
            ['cod' => 173, 'des' => 'BARRANCO DE LOBA', 'coddep' => '6'],
            ['cod' => 174, 'des' => 'CALAMAR', 'coddep' => '6'],
            ['cod' => 175, 'des' => 'CANTAGALLO', 'coddep' => '6'],
            ['cod' => 176, 'des' => 'CARTAGENA', 'coddep' => '6'],
            ['cod' => 177, 'des' => 'CICUCO', 'coddep' => '6'],
            ['cod' => 178, 'des' => 'CLEMENCIA', 'coddep' => '6'],
            ['cod' => 179, 'des' => 'CORDOBA', 'coddep' => '6'],
            ['cod' => 180, 'des' => 'EL CARMEN DE BOLIVAR', 'coddep' => '6'],
            ['cod' => 181, 'des' => 'EL GUAMO', 'coddep' => '6'],
            ['cod' => 182, 'des' => 'EL PEÑON', 'coddep' => '6'],
            ['cod' => 183, 'des' => 'HATILLO DE LOBA', 'coddep' => '6'],
            ['cod' => 184, 'des' => 'MAGANGUE', 'coddep' => '6'],
            ['cod' => 185, 'des' => 'MAHATES', 'coddep' => '6'],
            ['cod' => 186, 'des' => 'MARGARITA', 'coddep' => '6'],
            ['cod' => 187, 'des' => 'MARIA LA BAJA', 'coddep' => '6'],
            ['cod' => 188, 'des' => 'MOMPOS', 'coddep' => '6'],
            ['cod' => 189, 'des' => 'MONTECRISTO', 'coddep' => '6'],
            ['cod' => 190, 'des' => 'MORALES', 'coddep' => '6'],
            ['cod' => 191, 'des' => 'NOROSI', 'coddep' => '6'],
            ['cod' => 192, 'des' => 'PINILLOS', 'coddep' => '6'],
            ['cod' => 193, 'des' => 'REGIDOR', 'coddep' => '6'],
            ['cod' => 194, 'des' => 'RIO VIEJO', 'coddep' => '6'],
            ['cod' => 195, 'des' => 'SAN CRISTOBAL', 'coddep' => '6'],
            ['cod' => 196, 'des' => 'SAN ESTANISLAO', 'coddep' => '6'],
            ['cod' => 197, 'des' => 'SAN FERNANDO', 'coddep' => '6'],
            ['cod' => 198, 'des' => 'SAN JACINTO', 'coddep' => '6'],
            ['cod' => 199, 'des' => 'SAN JACINTO DEL CAUCA', 'coddep' => '6'],
            ['cod' => 200, 'des' => 'SAN JUAN NEPOMUCENO', 'coddep' => '6'],
            ['cod' => 201, 'des' => 'SAN MARTIN DE LOBA', 'coddep' => '6'],
            ['cod' => 202, 'des' => 'SAN PABLO', 'coddep' => '6'],
            ['cod' => 203, 'des' => 'SANTA CATALINA', 'coddep' => '6'],
            ['cod' => 204, 'des' => 'SANTA ROSA', 'coddep' => '6'],
            ['cod' => 205, 'des' => 'SANTA ROSA DEL SUR', 'coddep' => '6'],
            ['cod' => 206, 'des' => 'SIMITI', 'coddep' => '6'],
            ['cod' => 207, 'des' => 'SOPLAVIENTO', 'coddep' => '6'],
            ['cod' => 208, 'des' => 'TALAIGUA NUEVO', 'coddep' => '6'],
            ['cod' => 209, 'des' => 'TIQUISIO', 'coddep' => '6'],
            ['cod' => 210, 'des' => 'TURBACO', 'coddep' => '6'],
            ['cod' => 211, 'des' => 'TURBANA', 'coddep' => '6'],
            ['cod' => 212, 'des' => 'VILLANUEVA', 'coddep' => '6'],
            ['cod' => 213, 'des' => 'ZAMBRANO', 'coddep' => '6'],
            ['cod' => 214, 'des' => 'ALMEIDA', 'coddep' => '7'],
            ['cod' => 215, 'des' => 'AQUITANIA', 'coddep' => '7'],
            ['cod' => 216, 'des' => 'ARCABUCO', 'coddep' => '7'],
            ['cod' => 217, 'des' => 'BELEN', 'coddep' => '7'],
            ['cod' => 218, 'des' => 'BERBEO', 'coddep' => '7'],
            ['cod' => 219, 'des' => 'BETEITIVA', 'coddep' => '7'],
            ['cod' => 220, 'des' => 'BOAVITA', 'coddep' => '7'],
            ['cod' => 221, 'des' => 'BOYACA', 'coddep' => '7'],
            ['cod' => 222, 'des' => 'BRICEÑO', 'coddep' => '7'],
            ['cod' => 223, 'des' => 'BUENAVISTA', 'coddep' => '7'],
            ['cod' => 224, 'des' => 'BUSBANZA', 'coddep' => '7'],
            ['cod' => 225, 'des' => 'CALDAS', 'coddep' => '7'],
            ['cod' => 226, 'des' => 'CAMPOHERMOSO', 'coddep' => '7'],
            ['cod' => 227, 'des' => 'CERINZA', 'coddep' => '7'],
            ['cod' => 228, 'des' => 'CHINAVITA', 'coddep' => '7'],
            ['cod' => 229, 'des' => 'CHIQUINQUIRA', 'coddep' => '7'],
            ['cod' => 230, 'des' => 'CHIQUIZA', 'coddep' => '7'],
            ['cod' => 231, 'des' => 'CHISCAS', 'coddep' => '7'],
            ['cod' => 232, 'des' => 'CHITA', 'coddep' => '7'],
            ['cod' => 233, 'des' => 'CHITARAQUE', 'coddep' => '7'],
            ['cod' => 234, 'des' => 'CHIVATA', 'coddep' => '7'],
            ['cod' => 235, 'des' => 'CHIVOR', 'coddep' => '7'],
            ['cod' => 236, 'des' => 'CIENEGA', 'coddep' => '7'],
            ['cod' => 237, 'des' => 'COMBITA', 'coddep' => '7'],
            ['cod' => 238, 'des' => 'COPER', 'coddep' => '7'],
            ['cod' => 239, 'des' => 'CORRALES', 'coddep' => '7'],
            ['cod' => 240, 'des' => 'COVARACHIA', 'coddep' => '7'],
            ['cod' => 241, 'des' => 'CUBARA', 'coddep' => '7'],
            ['cod' => 242, 'des' => 'CUCAITA', 'coddep' => '7'],
            ['cod' => 243, 'des' => 'CUITIVA', 'coddep' => '7'],
            ['cod' => 244, 'des' => 'DUITAMA', 'coddep' => '7'],
            ['cod' => 245, 'des' => 'EL COCUY', 'coddep' => '7'],
            ['cod' => 246, 'des' => 'EL ESPINO', 'coddep' => '7'],
            ['cod' => 247, 'des' => 'FIRAVITOBA', 'coddep' => '7'],
            ['cod' => 248, 'des' => 'FLORESTA', 'coddep' => '7'],
            ['cod' => 249, 'des' => 'GACHANTIVA', 'coddep' => '7'],
            ['cod' => 250, 'des' => 'GAMEZA', 'coddep' => '7'],
            ['cod' => 251, 'des' => 'GARAGOA', 'coddep' => '7'],
            ['cod' => 252, 'des' => 'GUACAMAYAS', 'coddep' => '7'],
            ['cod' => 253, 'des' => 'GUATEQUE', 'coddep' => '7'],
            ['cod' => 254, 'des' => 'GUAYATA', 'coddep' => '7'],
            ['cod' => 255, 'des' => 'GÜICAN', 'coddep' => '7'],
            ['cod' => 256, 'des' => 'IZA', 'coddep' => '7'],
            ['cod' => 257, 'des' => 'JENESANO', 'coddep' => '7'],
            ['cod' => 258, 'des' => 'JERICO', 'coddep' => '7'],
            ['cod' => 259, 'des' => 'LA CAPILLA', 'coddep' => '7'],
            ['cod' => 260, 'des' => 'LA UVITA', 'coddep' => '7'],
            ['cod' => 261, 'des' => 'LA VICTORIA', 'coddep' => '7'],
            ['cod' => 262, 'des' => 'LABRANZAGRANDE', 'coddep' => '7'],
            ['cod' => 263, 'des' => 'MACANAL', 'coddep' => '7'],
            ['cod' => 264, 'des' => 'MARIPI', 'coddep' => '7'],
            ['cod' => 265, 'des' => 'MIRAFLORES', 'coddep' => '7'],
            ['cod' => 266, 'des' => 'MONGUA', 'coddep' => '7'],
            ['cod' => 267, 'des' => 'MONGUI', 'coddep' => '7'],
            ['cod' => 268, 'des' => 'MONIQUIRA', 'coddep' => '7'],
            ['cod' => 269, 'des' => 'MOTAVITA', 'coddep' => '7'],
            ['cod' => 270, 'des' => 'MUZO', 'coddep' => '7'],
            ['cod' => 271, 'des' => 'NOBSA', 'coddep' => '7'],
            ['cod' => 272, 'des' => 'NUEVO COLON', 'coddep' => '7'],
            ['cod' => 273, 'des' => 'OICATA', 'coddep' => '7'],
            ['cod' => 274, 'des' => 'OTANCHE', 'coddep' => '7'],
            ['cod' => 275, 'des' => 'PACHAVITA', 'coddep' => '7'],
            ['cod' => 276, 'des' => 'PAEZ', 'coddep' => '7'],
            ['cod' => 277, 'des' => 'PAIPA', 'coddep' => '7'],
            ['cod' => 278, 'des' => 'PAJARITO', 'coddep' => '7'],
            ['cod' => 279, 'des' => 'PANQUEBA', 'coddep' => '7'],
            ['cod' => 280, 'des' => 'PAUNA', 'coddep' => '7'],
            ['cod' => 281, 'des' => 'PAYA', 'coddep' => '7'],
            ['cod' => 282, 'des' => 'PAZ DE RIO', 'coddep' => '7'],
            ['cod' => 283, 'des' => 'PESCA', 'coddep' => '7'],
            ['cod' => 284, 'des' => 'PISBA', 'coddep' => '7'],
            ['cod' => 285, 'des' => 'PUERTO BOYACA', 'coddep' => '7'],
            ['cod' => 286, 'des' => 'QUIPAMA', 'coddep' => '7'],
            ['cod' => 287, 'des' => 'RAMIRIQUI', 'coddep' => '7'],
            ['cod' => 288, 'des' => 'RAQUIRA', 'coddep' => '7'],
            ['cod' => 289, 'des' => 'RONDON', 'coddep' => '7'],
            ['cod' => 290, 'des' => 'SABOYA', 'coddep' => '7'],
            ['cod' => 291, 'des' => 'SACHICA', 'coddep' => '7'],
            ['cod' => 292, 'des' => 'SAMACA', 'coddep' => '7'],
            ['cod' => 293, 'des' => 'SAN EDUARDO', 'coddep' => '7'],
            ['cod' => 294, 'des' => 'SAN JOSE DE PARE', 'coddep' => '7'],
            ['cod' => 295, 'des' => 'SAN LUIS DE GACENO', 'coddep' => '7'],
            ['cod' => 296, 'des' => 'SAN MATEO', 'coddep' => '7'],
            ['cod' => 297, 'des' => 'SAN MIGUEL DE SEMA', 'coddep' => '7'],
            ['cod' => 298, 'des' => 'SAN PABLO DE BORBUR', 'coddep' => '7'],
            ['cod' => 299, 'des' => 'SANTA MARIA', 'coddep' => '7'],
            ['cod' => 300, 'des' => 'SANTA ROSA DE VITERBO', 'coddep' => '7'],
            ['cod' => 301, 'des' => 'SANTA SOFIA', 'coddep' => '7'],
            ['cod' => 302, 'des' => 'SANTANA', 'coddep' => '7'],
            ['cod' => 303, 'des' => 'SATIVANORTE', 'coddep' => '7'],
            ['cod' => 304, 'des' => 'SATIVASUR', 'coddep' => '7'],
            ['cod' => 305, 'des' => 'SIACHOQUE', 'coddep' => '7'],
            ['cod' => 306, 'des' => 'SOATA', 'coddep' => '7'],
            ['cod' => 307, 'des' => 'SOCHA', 'coddep' => '7'],
            ['cod' => 308, 'des' => 'SOCOTA', 'coddep' => '7'],
            ['cod' => 309, 'des' => 'SOGAMOSO', 'coddep' => '7'],
            ['cod' => 310, 'des' => 'SOMONDOCO', 'coddep' => '7'],
            ['cod' => 311, 'des' => 'SORA', 'coddep' => '7'],
            ['cod' => 312, 'des' => 'SORACA', 'coddep' => '7'],
            ['cod' => 313, 'des' => 'SOTAQUIRA', 'coddep' => '7'],
            ['cod' => 314, 'des' => 'SUSACON', 'coddep' => '7'],
            ['cod' => 315, 'des' => 'SUTAMARCHAN', 'coddep' => '7'],
            ['cod' => 316, 'des' => 'SUTATENZA', 'coddep' => '7'],
            ['cod' => 317, 'des' => 'TASCO', 'coddep' => '7'],
            ['cod' => 318, 'des' => 'TENZA', 'coddep' => '7'],
            ['cod' => 319, 'des' => 'TIBANA', 'coddep' => '7'],
            ['cod' => 320, 'des' => 'TIBASOSA', 'coddep' => '7'],
            ['cod' => 321, 'des' => 'TINJACA', 'coddep' => '7'],
            ['cod' => 322, 'des' => 'TIPACOQUE', 'coddep' => '7'],
            ['cod' => 323, 'des' => 'TOCA', 'coddep' => '7'],
            ['cod' => 324, 'des' => 'TOGÜI', 'coddep' => '7'],
            ['cod' => 325, 'des' => 'TOPAGA', 'coddep' => '7'],
            ['cod' => 326, 'des' => 'TOTA', 'coddep' => '7'],
            ['cod' => 327, 'des' => 'TUNJA', 'coddep' => '7'],
            ['cod' => 328, 'des' => 'TUNUNGUA', 'coddep' => '7'],
            ['cod' => 329, 'des' => 'TURMEQUE', 'coddep' => '7'],
            ['cod' => 330, 'des' => 'TUTA', 'coddep' => '7'],
            ['cod' => 331, 'des' => 'TUTAZA', 'coddep' => '7'],
            ['cod' => 332, 'des' => 'UMBITA', 'coddep' => '7'],
            ['cod' => 333, 'des' => 'VENTAQUEMADA', 'coddep' => '7'],
            ['cod' => 334, 'des' => 'VILLA DE LEYVA', 'coddep' => '7'],
            ['cod' => 335, 'des' => 'VIRACACHA', 'coddep' => '7'],
            ['cod' => 336, 'des' => 'ZETAQUIRA', 'coddep' => '7'],
            ['cod' => 337, 'des' => 'AGUADAS', 'coddep' => '8'],
            ['cod' => 338, 'des' => 'ANSERMA', 'coddep' => '8'],
            ['cod' => 339, 'des' => 'ARANZAZU', 'coddep' => '8'],
            ['cod' => 340, 'des' => 'BELALCAZAR', 'coddep' => '8'],
            ['cod' => 341, 'des' => 'CHINCHINA', 'coddep' => '8'],
            ['cod' => 342, 'des' => 'FILADELFIA', 'coddep' => '8'],
            ['cod' => 343, 'des' => 'LA DORADA', 'coddep' => '8'],
            ['cod' => 344, 'des' => 'LA MERCED', 'coddep' => '8'],
            ['cod' => 345, 'des' => 'MANIZALES', 'coddep' => '8'],
            ['cod' => 346, 'des' => 'MANZANARES', 'coddep' => '8'],
            ['cod' => 347, 'des' => 'MARMATO', 'coddep' => '8'],
            ['cod' => 348, 'des' => 'MARQUETALIA', 'coddep' => '8'],
            ['cod' => 349, 'des' => 'MARULANDA', 'coddep' => '8'],
            ['cod' => 350, 'des' => 'NEIRA', 'coddep' => '8'],
            ['cod' => 351, 'des' => 'NORCASIA', 'coddep' => '8'],
            ['cod' => 352, 'des' => 'PACORA', 'coddep' => '8'],
            ['cod' => 353, 'des' => 'PALESTINA', 'coddep' => '8'],
            ['cod' => 354, 'des' => 'PENSILVANIA', 'coddep' => '8'],
            ['cod' => 355, 'des' => 'RIOSUCIO', 'coddep' => '8'],
            ['cod' => 356, 'des' => 'RISARALDA', 'coddep' => '8'],
            ['cod' => 357, 'des' => 'SALAMINA', 'coddep' => '8'],
            ['cod' => 358, 'des' => 'SAMANA', 'coddep' => '8'],
            ['cod' => 359, 'des' => 'SAN JOSE', 'coddep' => '8'],
            ['cod' => 360, 'des' => 'SUPIA', 'coddep' => '8'],
            ['cod' => 361, 'des' => 'VICTORIA', 'coddep' => '8'],
            ['cod' => 362, 'des' => 'VILLAMARIA', 'coddep' => '8'],
            ['cod' => 363, 'des' => 'VITERBO', 'coddep' => '8'],
            ['cod' => 364, 'des' => 'ALBANIA', 'coddep' => '9'],
            ['cod' => 365, 'des' => 'BELEN DE LOS ANDAQUIES', 'coddep' => '9'],
            ['cod' => 366, 'des' => 'CARTAGENA DEL CHAIRA', 'coddep' => '9'],
            ['cod' => 367, 'des' => 'CURILLO', 'coddep' => '9'],
            ['cod' => 368, 'des' => 'EL DONCELLO', 'coddep' => '9'],
            ['cod' => 369, 'des' => 'EL PAUJIL', 'coddep' => '9'],
            ['cod' => 370, 'des' => 'FLORENCIA', 'coddep' => '9'],
            ['cod' => 371, 'des' => 'LA MONTAÑITA', 'coddep' => '9'],
            ['cod' => 372, 'des' => 'MILAN', 'coddep' => '9'],
            ['cod' => 373, 'des' => 'MORELIA', 'coddep' => '9'],
            ['cod' => 374, 'des' => 'PUERTO RICO', 'coddep' => '9'],
            ['cod' => 375, 'des' => 'SAN JOSE DEL FRAGUA', 'coddep' => '9'],
            ['cod' => 376, 'des' => 'SAN VICENTE DEL CAGUAN', 'coddep' => '9'],
            ['cod' => 377, 'des' => 'SOLANO', 'coddep' => '9'],
            ['cod' => 378, 'des' => 'SOLITA', 'coddep' => '9'],
            ['cod' => 379, 'des' => 'VALPARAISO', 'coddep' => '9'],
            ['cod' => 380, 'des' => 'AGUAZUL', 'coddep' => '10'],
            ['cod' => 381, 'des' => 'CHAMEZA', 'coddep' => '10'],
            ['cod' => 382, 'des' => 'HATO COROZAL', 'coddep' => '10'],
            ['cod' => 383, 'des' => 'LA SALINA', 'coddep' => '10'],
            ['cod' => 384, 'des' => 'MANI', 'coddep' => '10'],
            ['cod' => 385, 'des' => 'MONTERREY', 'coddep' => '10'],
            ['cod' => 386, 'des' => 'NUNCHIA', 'coddep' => '10'],
            ['cod' => 387, 'des' => 'OROCUE', 'coddep' => '10'],
            ['cod' => 388, 'des' => 'PAZ DE ARIPORO', 'coddep' => '10'],
            ['cod' => 389, 'des' => 'PORE', 'coddep' => '10'],
            ['cod' => 390, 'des' => 'RECETOR', 'coddep' => '10'],
            ['cod' => 391, 'des' => 'SABANALARGA', 'coddep' => '10'],
            ['cod' => 392, 'des' => 'SACAMA', 'coddep' => '10'],
            ['cod' => 393, 'des' => 'SAN LUIS DE PALENQUE', 'coddep' => '10'],
            ['cod' => 394, 'des' => 'TAMARA', 'coddep' => '10'],
            ['cod' => 395, 'des' => 'TAURAMENA', 'coddep' => '10'],
            ['cod' => 396, 'des' => 'TRINIDAD', 'coddep' => '10'],
            ['cod' => 397, 'des' => 'VILLANUEVA', 'coddep' => '10'],
            ['cod' => 398, 'des' => 'YOPAL', 'coddep' => '10'],
            ['cod' => 399, 'des' => 'ALMAGUER', 'coddep' => '11'],
            ['cod' => 400, 'des' => 'ARGELIA', 'coddep' => '11'],
            ['cod' => 401, 'des' => 'BALBOA', 'coddep' => '11'],
            ['cod' => 402, 'des' => 'BOLIVAR', 'coddep' => '11'],
            ['cod' => 403, 'des' => 'BUENOS AIRES', 'coddep' => '11'],
            ['cod' => 404, 'des' => 'CAJIBIO', 'coddep' => '11'],
            ['cod' => 405, 'des' => 'CALDONO', 'coddep' => '11'],
            ['cod' => 406, 'des' => 'CALOTO', 'coddep' => '11'],
            ['cod' => 407, 'des' => 'CORINTO', 'coddep' => '11'],
            ['cod' => 408, 'des' => 'EL TAMBO', 'coddep' => '11'],
            ['cod' => 409, 'des' => 'FLORENCIA', 'coddep' => '11'],
            ['cod' => 410, 'des' => 'GUACHENE', 'coddep' => '11'],
            ['cod' => 411, 'des' => 'GUAPI', 'coddep' => '11'],
            ['cod' => 412, 'des' => 'INZA', 'coddep' => '11'],
            ['cod' => 413, 'des' => 'JAMBALO', 'coddep' => '11'],
            ['cod' => 414, 'des' => 'LA SIERRA', 'coddep' => '11'],
            ['cod' => 415, 'des' => 'LA VEGA', 'coddep' => '11'],
            ['cod' => 416, 'des' => 'LOPEZ', 'coddep' => '11'],
            ['cod' => 417, 'des' => 'MERCADERES', 'coddep' => '11'],
            ['cod' => 418, 'des' => 'MIRANDA', 'coddep' => '11'],
            ['cod' => 419, 'des' => 'MORALES', 'coddep' => '11'],
            ['cod' => 420, 'des' => 'PADILLA', 'coddep' => '11'],
            ['cod' => 421, 'des' => 'PAEZ', 'coddep' => '11'],
            ['cod' => 422, 'des' => 'PATIA', 'coddep' => '11'],
            ['cod' => 423, 'des' => 'PIAMONTE', 'coddep' => '11'],
            ['cod' => 424, 'des' => 'PIENDAMO', 'coddep' => '11'],
            ['cod' => 425, 'des' => 'POPAYAN', 'coddep' => '11'],
            ['cod' => 426, 'des' => 'PUERTO TEJADA', 'coddep' => '11'],
            ['cod' => 427, 'des' => 'PURACE', 'coddep' => '11'],
            ['cod' => 428, 'des' => 'ROSAS', 'coddep' => '11'],
            ['cod' => 429, 'des' => 'SAN SEBASTIAN', 'coddep' => '11'],
            ['cod' => 430, 'des' => 'SANTA ROSA', 'coddep' => '11'],
            ['cod' => 431, 'des' => 'SANTANDER DE QUILICHAO', 'coddep' => '11'],
            ['cod' => 432, 'des' => 'SILVIA', 'coddep' => '11'],
            ['cod' => 433, 'des' => 'SOTARA', 'coddep' => '11'],
            ['cod' => 434, 'des' => 'SUAREZ', 'coddep' => '11'],
            ['cod' => 435, 'des' => 'SUCRE', 'coddep' => '11'],
            ['cod' => 436, 'des' => 'TIMBIO', 'coddep' => '11'],
            ['cod' => 437, 'des' => 'TIMBIQUI', 'coddep' => '11'],
            ['cod' => 438, 'des' => 'TORIBIO', 'coddep' => '11'],
            ['cod' => 439, 'des' => 'TOTORO', 'coddep' => '11'],
            ['cod' => 440, 'des' => 'VILLA RICA', 'coddep' => '11'],
            ['cod' => 441, 'des' => 'AGUACHICA', 'coddep' => '12'],
            ['cod' => 442, 'des' => 'AGUSTIN CODAZZI', 'coddep' => '12'],
            ['cod' => 443, 'des' => 'ASTREA', 'coddep' => '12'],
            ['cod' => 444, 'des' => 'BECERRIL', 'coddep' => '12'],
            ['cod' => 445, 'des' => 'BOSCONIA', 'coddep' => '12'],
            ['cod' => 446, 'des' => 'CHIMICHAGUA', 'coddep' => '12'],
            ['cod' => 447, 'des' => 'CHIRIGUANA', 'coddep' => '12'],
            ['cod' => 448, 'des' => 'CURUMANI', 'coddep' => '12'],
            ['cod' => 449, 'des' => 'EL COPEY', 'coddep' => '12'],
            ['cod' => 450, 'des' => 'EL PASO', 'coddep' => '12'],
            ['cod' => 451, 'des' => 'GAMARRA', 'coddep' => '12'],
            ['cod' => 452, 'des' => 'GONZALEZ', 'coddep' => '12'],
            ['cod' => 453, 'des' => 'LA GLORIA', 'coddep' => '12'],
            ['cod' => 454, 'des' => 'LA JAGUA DE IBIRICO', 'coddep' => '12'],
            ['cod' => 455, 'des' => 'LA PAZ', 'coddep' => '12'],
            ['cod' => 456, 'des' => 'MANAURE', 'coddep' => '12'],
            ['cod' => 457, 'des' => 'PAILITAS', 'coddep' => '12'],
            ['cod' => 458, 'des' => 'PELAYA', 'coddep' => '12'],
            ['cod' => 459, 'des' => 'PUEBLO BELLO', 'coddep' => '12'],
            ['cod' => 460, 'des' => 'RIO DE ORO', 'coddep' => '12'],
            ['cod' => 461, 'des' => 'SAN ALBERTO', 'coddep' => '12'],
            ['cod' => 462, 'des' => 'SAN DIEGO', 'coddep' => '12'],
            ['cod' => 463, 'des' => 'SAN MARTIN', 'coddep' => '12'],
            ['cod' => 464, 'des' => 'TAMALAMEQUE', 'coddep' => '12'],
            ['cod' => 465, 'des' => 'VALLEDUPAR', 'coddep' => '12'],
            ['cod' => 466, 'des' => 'ACANDI', 'coddep' => '13'],
            ['cod' => 467, 'des' => 'ALTO BAUDO', 'coddep' => '13'],
            ['cod' => 468, 'des' => 'ATRATO', 'coddep' => '13'],
            ['cod' => 469, 'des' => 'BAGADO', 'coddep' => '13'],
            ['cod' => 470, 'des' => 'BAHIA SOLANO', 'coddep' => '13'],
            ['cod' => 471, 'des' => 'BAJO BAUDO', 'coddep' => '13'],
            ['cod' => 472, 'des' => 'BELEN DE BAJIRA', 'coddep' => '13'],
            ['cod' => 473, 'des' => 'BOJAYA', 'coddep' => '13'],
            ['cod' => 474, 'des' => 'CARMEN DEL DARIEN', 'coddep' => '13'],
            ['cod' => 475, 'des' => 'CERTEGUI', 'coddep' => '13'],
            ['cod' => 476, 'des' => 'CONDOTO', 'coddep' => '13'],
            ['cod' => 477, 'des' => 'EL CANTON DEL SAN PABLO', 'coddep' => '13'],
            ['cod' => 478, 'des' => 'EL CARMEN DE ATRATO', 'coddep' => '13'],
            ['cod' => 479, 'des' => 'EL LITORAL DEL SAN JUAN', 'coddep' => '13'],
            ['cod' => 480, 'des' => 'ISTMINA', 'coddep' => '13'],
            ['cod' => 481, 'des' => 'JURADO', 'coddep' => '13'],
            ['cod' => 482, 'des' => 'LLORO', 'coddep' => '13'],
            ['cod' => 483, 'des' => 'MEDIO ATRATO', 'coddep' => '13'],
            ['cod' => 484, 'des' => 'MEDIO BAUDO', 'coddep' => '13'],
            ['cod' => 485, 'des' => 'MEDIO SAN JUAN', 'coddep' => '13'],
            ['cod' => 486, 'des' => 'NOVITA', 'coddep' => '13'],
            ['cod' => 487, 'des' => 'NUQUI', 'coddep' => '13'],
            ['cod' => 488, 'des' => 'QUIBDO', 'coddep' => '13'],
            ['cod' => 489, 'des' => 'RIO IRO', 'coddep' => '13'],
            ['cod' => 490, 'des' => 'RIO QUITO', 'coddep' => '13'],
            ['cod' => 491, 'des' => 'RIOSUCIO', 'coddep' => '13'],
            ['cod' => 492, 'des' => 'SAN JOSE DEL PALMAR', 'coddep' => '13'],
            ['cod' => 493, 'des' => 'SIPI', 'coddep' => '13'],
            ['cod' => 494, 'des' => 'TADO', 'coddep' => '13'],
            ['cod' => 495, 'des' => 'UNGUIA', 'coddep' => '13'],
            ['cod' => 496, 'des' => 'UNION PANAMERICANA', 'coddep' => '13'],
            ['cod' => 497, 'des' => 'AYAPEL', 'coddep' => '14'],
            ['cod' => 498, 'des' => 'BUENAVISTA', 'coddep' => '14'],
            ['cod' => 499, 'des' => 'CANALETE', 'coddep' => '14'],
            ['cod' => 500, 'des' => 'CERETE', 'coddep' => '14'],
            ['cod' => 501, 'des' => 'CHIMA', 'coddep' => '14'],
            ['cod' => 502, 'des' => 'CHINU', 'coddep' => '14'],
            ['cod' => 503, 'des' => 'CIENAGA DE ORO', 'coddep' => '14'],
            ['cod' => 504, 'des' => 'COTORRA', 'coddep' => '14'],
            ['cod' => 505, 'des' => 'LA APARTADA', 'coddep' => '14'],
            ['cod' => 506, 'des' => 'LORICA', 'coddep' => '14'],
            ['cod' => 507, 'des' => 'LOS CORDOBAS', 'coddep' => '14'],
            ['cod' => 508, 'des' => 'MOMIL', 'coddep' => '14'],
            ['cod' => 509, 'des' => 'MONTELIBANO', 'coddep' => '14'],
            ['cod' => 510, 'des' => 'MONTERIA', 'coddep' => '14'],
            ['cod' => 511, 'des' => 'MOÑITOS', 'coddep' => '14'],
            ['cod' => 512, 'des' => 'PLANETA RICA', 'coddep' => '14'],
            ['cod' => 513, 'des' => 'PUEBLO NUEVO', 'coddep' => '14'],
            ['cod' => 514, 'des' => 'PUERTO ESCONDIDO', 'coddep' => '14'],
            ['cod' => 515, 'des' => 'PUERTO LIBERTADOR', 'coddep' => '14'],
            ['cod' => 516, 'des' => 'PURISIMA', 'coddep' => '14'],
            ['cod' => 517, 'des' => 'SAHAGUN', 'coddep' => '14'],
            ['cod' => 518, 'des' => 'SAN ANDRES SOTAVENTO', 'coddep' => '14'],
            ['cod' => 519, 'des' => 'SAN ANTERO', 'coddep' => '14'],
            ['cod' => 520, 'des' => 'SAN BERNARDO DEL VIENTO', 'coddep' => '14'],
            ['cod' => 521, 'des' => 'SAN CARLOS', 'coddep' => '14'],
            ['cod' => 522, 'des' => 'SAN JOSE DE URE', 'coddep' => '14'],
            ['cod' => 523, 'des' => 'SAN PELAYO', 'coddep' => '14'],
            ['cod' => 524, 'des' => 'TIERRALTA', 'coddep' => '14'],
            ['cod' => 525, 'des' => 'TUCHIN', 'coddep' => '14'],
            ['cod' => 526, 'des' => 'VALENCIA', 'coddep' => '14'],
            ['cod' => 527, 'des' => 'AGUA DE DIOS', 'coddep' => '15'],
            ['cod' => 528, 'des' => 'ALBAN', 'coddep' => '15'],
            ['cod' => 529, 'des' => 'ANAPOIMA', 'coddep' => '15'],
            ['cod' => 530, 'des' => 'ANOLAIMA', 'coddep' => '15'],
            ['cod' => 531, 'des' => 'APULO', 'coddep' => '15'],
            ['cod' => 532, 'des' => 'ARBELAEZ', 'coddep' => '15'],
            ['cod' => 533, 'des' => 'BELTRAN', 'coddep' => '15'],
            ['cod' => 534, 'des' => 'BITUIMA', 'coddep' => '15'],
            ['cod' => 535, 'des' => 'BOJACA', 'coddep' => '15'],
            ['cod' => 536, 'des' => 'CABRERA', 'coddep' => '15'],
            ['cod' => 537, 'des' => 'CACHIPAY', 'coddep' => '15'],
            ['cod' => 538, 'des' => 'CAJICA', 'coddep' => '15'],
            ['cod' => 539, 'des' => 'CAPARRAPI', 'coddep' => '15'],
            ['cod' => 540, 'des' => 'CAQUEZA', 'coddep' => '15'],
            ['cod' => 541, 'des' => 'CARMEN DE CARUPA', 'coddep' => '15'],
            ['cod' => 542, 'des' => 'CHAGUANI', 'coddep' => '15'],
            ['cod' => 543, 'des' => 'CHIA', 'coddep' => '15'],
            ['cod' => 544, 'des' => 'CHIPAQUE', 'coddep' => '15'],
            ['cod' => 545, 'des' => 'CHOACHI', 'coddep' => '15'],
            ['cod' => 546, 'des' => 'CHOCONTA', 'coddep' => '15'],
            ['cod' => 547, 'des' => 'COGUA', 'coddep' => '15'],
            ['cod' => 548, 'des' => 'COTA', 'coddep' => '15'],
            ['cod' => 549, 'des' => 'CUCUNUBA', 'coddep' => '15'],
            ['cod' => 550, 'des' => 'EL COLEGIO', 'coddep' => '15'],
            ['cod' => 551, 'des' => 'EL PEÑON', 'coddep' => '15'],
            ['cod' => 552, 'des' => 'EL ROSAL', 'coddep' => '15'],
            ['cod' => 553, 'des' => 'FACATATIVA', 'coddep' => '15'],
            ['cod' => 554, 'des' => 'FOMEQUE', 'coddep' => '15'],
            ['cod' => 555, 'des' => 'FOSCA', 'coddep' => '15'],
            ['cod' => 556, 'des' => 'FUNZA', 'coddep' => '15'],
            ['cod' => 557, 'des' => 'FUQUENE', 'coddep' => '15'],
            ['cod' => 558, 'des' => 'FUSAGASUGA', 'coddep' => '15'],
            ['cod' => 559, 'des' => 'GACHALA', 'coddep' => '15'],
            ['cod' => 560, 'des' => 'GACHANCIPA', 'coddep' => '15'],
            ['cod' => 561, 'des' => 'GACHETA', 'coddep' => '15'],
            ['cod' => 562, 'des' => 'GAMA', 'coddep' => '15'],
            ['cod' => 563, 'des' => 'GIRARDOT', 'coddep' => '15'],
            ['cod' => 564, 'des' => 'GRANADA', 'coddep' => '15'],
            ['cod' => 565, 'des' => 'GUACHETA', 'coddep' => '15'],
            ['cod' => 566, 'des' => 'GUADUAS', 'coddep' => '15'],
            ['cod' => 567, 'des' => 'GUASCA', 'coddep' => '15'],
            ['cod' => 568, 'des' => 'GUATAQUI', 'coddep' => '15'],
            ['cod' => 569, 'des' => 'GUATAVITA', 'coddep' => '15'],
            ['cod' => 570, 'des' => 'GUAYABAL DE SIQUIMA', 'coddep' => '15'],
            ['cod' => 571, 'des' => 'GUAYABETAL', 'coddep' => '15'],
            ['cod' => 572, 'des' => 'GUTIERREZ', 'coddep' => '15'],
            ['cod' => 573, 'des' => 'JERUSALEN', 'coddep' => '15'],
            ['cod' => 574, 'des' => 'JUNIN', 'coddep' => '15'],
            ['cod' => 575, 'des' => 'LA CALERA', 'coddep' => '15'],
            ['cod' => 576, 'des' => 'LA MESA', 'coddep' => '15'],
            ['cod' => 577, 'des' => 'LA PALMA', 'coddep' => '15'],
            ['cod' => 578, 'des' => 'LA PEÑA', 'coddep' => '15'],
            ['cod' => 579, 'des' => 'LA VEGA', 'coddep' => '15'],
            ['cod' => 580, 'des' => 'LENGUAZAQUE', 'coddep' => '15'],
            ['cod' => 581, 'des' => 'MACHETA', 'coddep' => '15'],
            ['cod' => 582, 'des' => 'MADRID', 'coddep' => '15'],
            ['cod' => 583, 'des' => 'MANTA', 'coddep' => '15'],
            ['cod' => 584, 'des' => 'MEDINA', 'coddep' => '15'],
            ['cod' => 585, 'des' => 'MOSQUERA', 'coddep' => '15'],
            ['cod' => 586, 'des' => 'NARIÑO', 'coddep' => '15'],
            ['cod' => 587, 'des' => 'NEMOCON', 'coddep' => '15'],
            ['cod' => 588, 'des' => 'NILO', 'coddep' => '15'],
            ['cod' => 589, 'des' => 'NIMAIMA', 'coddep' => '15'],
            ['cod' => 590, 'des' => 'NOCAIMA', 'coddep' => '15'],
            ['cod' => 591, 'des' => 'PACHO', 'coddep' => '15'],
            ['cod' => 592, 'des' => 'PAIME', 'coddep' => '15'],
            ['cod' => 593, 'des' => 'PANDI', 'coddep' => '15'],
            ['cod' => 594, 'des' => 'PARATEBUENO', 'coddep' => '15'],
            ['cod' => 595, 'des' => 'PASCA', 'coddep' => '15'],
            ['cod' => 596, 'des' => 'PUERTO SALGAR', 'coddep' => '15'],
            ['cod' => 597, 'des' => 'PULI', 'coddep' => '15'],
            ['cod' => 598, 'des' => 'QUEBRADANEGRA', 'coddep' => '15'],
            ['cod' => 599, 'des' => 'QUETAME', 'coddep' => '15'],
            ['cod' => 600, 'des' => 'QUIPILE', 'coddep' => '15'],
            ['cod' => 601, 'des' => 'RICAURTE', 'coddep' => '15'],
            ['cod' => 602, 'des' => 'SAN ANTONIO DEL TEQUENDAMA', 'coddep' => '15'],
            ['cod' => 603, 'des' => 'SAN BERNARDO', 'coddep' => '15'],
            ['cod' => 604, 'des' => 'SAN CAYETANO', 'coddep' => '15'],
            ['cod' => 605, 'des' => 'SAN FRANCISCO', 'coddep' => '15'],
            ['cod' => 606, 'des' => 'SAN JUAN DE RIO SECO', 'coddep' => '15'],
            ['cod' => 607, 'des' => 'SASAIMA', 'coddep' => '15'],
            ['cod' => 608, 'des' => 'SESQUILE', 'coddep' => '15'],
            ['cod' => 609, 'des' => 'SIBATE', 'coddep' => '15'],
            ['cod' => 610, 'des' => 'SILVANIA', 'coddep' => '15'],
            ['cod' => 611, 'des' => 'SIMIJACA', 'coddep' => '15'],
            ['cod' => 612, 'des' => 'SOACHA', 'coddep' => '15'],
            ['cod' => 613, 'des' => 'SOPO', 'coddep' => '15'],
            ['cod' => 614, 'des' => 'SUBACHOQUE', 'coddep' => '15'],
            ['cod' => 615, 'des' => 'SUESCA', 'coddep' => '15'],
            ['cod' => 616, 'des' => 'SUPATA', 'coddep' => '15'],
            ['cod' => 617, 'des' => 'SUSA', 'coddep' => '15'],
            ['cod' => 618, 'des' => 'SUTATAUSA', 'coddep' => '15'],
            ['cod' => 619, 'des' => 'TABIO', 'coddep' => '15'],
            ['cod' => 620, 'des' => 'TAUSA', 'coddep' => '15'],
            ['cod' => 621, 'des' => 'TENA', 'coddep' => '15'],
            ['cod' => 622, 'des' => 'TENJO', 'coddep' => '15'],
            ['cod' => 623, 'des' => 'TIBACUY', 'coddep' => '15'],
            ['cod' => 624, 'des' => 'TIBIRITA', 'coddep' => '15'],
            ['cod' => 625, 'des' => 'TOCAIMA', 'coddep' => '15'],
            ['cod' => 626, 'des' => 'TOCANCIPA', 'coddep' => '15'],
            ['cod' => 627, 'des' => 'TOPAIPI', 'coddep' => '15'],
            ['cod' => 628, 'des' => 'UBALA', 'coddep' => '15'],
            ['cod' => 629, 'des' => 'UBAQUE', 'coddep' => '15'],
            ['cod' => 630, 'des' => 'UNE', 'coddep' => '15'],
            ['cod' => 631, 'des' => 'UTICA', 'coddep' => '15'],
            ['cod' => 632, 'des' => 'VENECIA', 'coddep' => '15'],
            ['cod' => 633, 'des' => 'VERGARA', 'coddep' => '15'],
            ['cod' => 634, 'des' => 'VIANI', 'coddep' => '15'],
            ['cod' => 635, 'des' => 'VILLA DE SAN DIEGO DE UBATE', 'coddep' => '15'],
            ['cod' => 636, 'des' => 'VILLAGOMEZ', 'coddep' => '15'],
            ['cod' => 637, 'des' => 'VILLAPINZON', 'coddep' => '15'],
            ['cod' => 638, 'des' => 'VILLETA', 'coddep' => '15'],
            ['cod' => 639, 'des' => 'VIOTA', 'coddep' => '15'],
            ['cod' => 640, 'des' => 'YACOPI', 'coddep' => '15'],
            ['cod' => 641, 'des' => 'ZIPACON', 'coddep' => '15'],
            ['cod' => 642, 'des' => 'ZIPAQUIRA', 'coddep' => '15'],
            ['cod' => 643, 'des' => 'BARRANCO MINAS', 'coddep' => '16'],
            ['cod' => 644, 'des' => 'CACAHUAL', 'coddep' => '16'],
            ['cod' => 645, 'des' => 'INIRIDA', 'coddep' => '16'],
            ['cod' => 646, 'des' => 'LA GUADALUPE', 'coddep' => '16'],
            ['cod' => 647, 'des' => 'MAPIRIPANA', 'coddep' => '16'],
            ['cod' => 648, 'des' => 'MORICHAL', 'coddep' => '16'],
            ['cod' => 649, 'des' => 'PANA PANA', 'coddep' => '16'],
            ['cod' => 650, 'des' => 'PUERTO COLOMBIA', 'coddep' => '16'],
            ['cod' => 651, 'des' => 'SAN FELIPE', 'coddep' => '16'],
            ['cod' => 652, 'des' => 'CALAMAR', 'coddep' => '17'],
            ['cod' => 653, 'des' => 'EL RETORNO', 'coddep' => '17'],
            ['cod' => 654, 'des' => 'MIRAFLORES', 'coddep' => '17'],
            ['cod' => 655, 'des' => 'SAN JOSE DEL GUAVIARE', 'coddep' => '17'],
            ['cod' => 656, 'des' => 'ACEVEDO', 'coddep' => '18'],
            ['cod' => 657, 'des' => 'AGRADO', 'coddep' => '18'],
            ['cod' => 658, 'des' => 'AIPE', 'coddep' => '18'],
            ['cod' => 659, 'des' => 'ALGECIRAS', 'coddep' => '18'],
            ['cod' => 660, 'des' => 'ALTAMIRA', 'coddep' => '18'],
            ['cod' => 661, 'des' => 'BARAYA', 'coddep' => '18'],
            ['cod' => 662, 'des' => 'CAMPOALEGRE', 'coddep' => '18'],
            ['cod' => 663, 'des' => 'COLOMBIA', 'coddep' => '18'],
            ['cod' => 664, 'des' => 'ELIAS', 'coddep' => '18'],
            ['cod' => 665, 'des' => 'GARZON', 'coddep' => '18'],
            ['cod' => 666, 'des' => 'GIGANTE', 'coddep' => '18'],
            ['cod' => 667, 'des' => 'GUADALUPE', 'coddep' => '18'],
            ['cod' => 668, 'des' => 'HOBO', 'coddep' => '18'],
            ['cod' => 669, 'des' => 'IQUIRA', 'coddep' => '18'],
            ['cod' => 670, 'des' => 'ISNOS', 'coddep' => '18'],
            ['cod' => 671, 'des' => 'LA ARGENTINA', 'coddep' => '18'],
            ['cod' => 672, 'des' => 'LA PLATA', 'coddep' => '18'],
            ['cod' => 673, 'des' => 'NATAGA', 'coddep' => '18'],
            ['cod' => 674, 'des' => 'NEIVA', 'coddep' => '18'],
            ['cod' => 675, 'des' => 'OPORAPA', 'coddep' => '18'],
            ['cod' => 676, 'des' => 'PAICOL', 'coddep' => '18'],
            ['cod' => 677, 'des' => 'PALERMO', 'coddep' => '18'],
            ['cod' => 678, 'des' => 'PALESTINA', 'coddep' => '18'],
            ['cod' => 679, 'des' => 'PITAL', 'coddep' => '18'],
            ['cod' => 680, 'des' => 'PITALITO', 'coddep' => '18'],
            ['cod' => 681, 'des' => 'RIVERA', 'coddep' => '18'],
            ['cod' => 682, 'des' => 'SALADOBLANCO', 'coddep' => '18'],
            ['cod' => 683, 'des' => 'SAN AGUSTIN', 'coddep' => '18'],
            ['cod' => 684, 'des' => 'SANTA MARIA', 'coddep' => '18'],
            ['cod' => 685, 'des' => 'SUAZA', 'coddep' => '18'],
            ['cod' => 686, 'des' => 'TARQUI', 'coddep' => '18'],
            ['cod' => 687, 'des' => 'TELLO', 'coddep' => '18'],
            ['cod' => 688, 'des' => 'TERUEL', 'coddep' => '18'],
            ['cod' => 689, 'des' => 'TESALIA', 'coddep' => '18'],
            ['cod' => 690, 'des' => 'TIMANA', 'coddep' => '18'],
            ['cod' => 691, 'des' => 'VILLAVIEJA', 'coddep' => '18'],
            ['cod' => 692, 'des' => 'YAGUARA', 'coddep' => '18'],
            ['cod' => 693, 'des' => 'ALBANIA', 'coddep' => '19'],
            ['cod' => 694, 'des' => 'BARRANCAS', 'coddep' => '19'],
            ['cod' => 695, 'des' => 'DIBULLA', 'coddep' => '19'],
            ['cod' => 696, 'des' => 'DISTRACCION', 'coddep' => '19'],
            ['cod' => 697, 'des' => 'EL MOLINO', 'coddep' => '19'],
            ['cod' => 698, 'des' => 'FONSECA', 'coddep' => '19'],
            ['cod' => 699, 'des' => 'HATONUEVO', 'coddep' => '19'],
            ['cod' => 700, 'des' => 'LA JAGUA DEL PILAR', 'coddep' => '19'],
            ['cod' => 701, 'des' => 'MAICAO', 'coddep' => '19'],
            ['cod' => 702, 'des' => 'MANAURE', 'coddep' => '19'],
            ['cod' => 703, 'des' => 'RIOHACHA', 'coddep' => '19'],
            ['cod' => 704, 'des' => 'SAN JUAN DEL CESAR', 'coddep' => '19'],
            ['cod' => 705, 'des' => 'URIBIA', 'coddep' => '19'],
            ['cod' => 706, 'des' => 'URUMITA', 'coddep' => '19'],
            ['cod' => 707, 'des' => 'VILLANUEVA', 'coddep' => '19'],
            ['cod' => 708, 'des' => 'ALGARROBO', 'coddep' => '20'],
            ['cod' => 709, 'des' => 'ARACATACA', 'coddep' => '20'],
            ['cod' => 710, 'des' => 'ARIGUANI', 'coddep' => '20'],
            ['cod' => 711, 'des' => 'CERRO SAN ANTONIO', 'coddep' => '20'],
            ['cod' => 712, 'des' => 'CHIVOLO', 'coddep' => '20'],
            ['cod' => 713, 'des' => 'CIENAGA', 'coddep' => '20'],
            ['cod' => 714, 'des' => 'CONCORDIA', 'coddep' => '20'],
            ['cod' => 715, 'des' => 'EL BANCO', 'coddep' => '20'],
            ['cod' => 716, 'des' => 'EL PIÑON', 'coddep' => '20'],
            ['cod' => 717, 'des' => 'EL RETEN', 'coddep' => '20'],
            ['cod' => 718, 'des' => 'FUNDACION', 'coddep' => '20'],
            ['cod' => 719, 'des' => 'GUAMAL', 'coddep' => '20'],
            ['cod' => 720, 'des' => 'NUEVA GRANADA', 'coddep' => '20'],
            ['cod' => 721, 'des' => 'PEDRAZA', 'coddep' => '20'],
            ['cod' => 722, 'des' => 'PIJIÑO DEL CARMEN', 'coddep' => '20'],
            ['cod' => 723, 'des' => 'PIVIJAY', 'coddep' => '20'],
            ['cod' => 724, 'des' => 'PLATO', 'coddep' => '20'],
            ['cod' => 725, 'des' => 'PUEBLOVIEJO', 'coddep' => '20'],
            ['cod' => 726, 'des' => 'REMOLINO', 'coddep' => '20'],
            ['cod' => 727, 'des' => 'SABANAS DE SAN ANGEL', 'coddep' => '20'],
            ['cod' => 728, 'des' => 'SALAMINA', 'coddep' => '20'],
            ['cod' => 729, 'des' => 'SAN SEBASTIAN DE BUENAVISTA', 'coddep' => '20'],
            ['cod' => 730, 'des' => 'SAN ZENON', 'coddep' => '20'],
            ['cod' => 731, 'des' => 'SANTA ANA', 'coddep' => '20'],
            ['cod' => 732, 'des' => 'SANTA BARBARA DE PINTO', 'coddep' => '20'],
            ['cod' => 733, 'des' => 'SANTA MARTA', 'coddep' => '20'],
            ['cod' => 734, 'des' => 'SITIONUEVO', 'coddep' => '20'],
            ['cod' => 735, 'des' => 'TENERIFE', 'coddep' => '20'],
            ['cod' => 736, 'des' => 'ZAPAYAN', 'coddep' => '20'],
            ['cod' => 737, 'des' => 'ZONA BANANERA', 'coddep' => '20'],
            ['cod' => 738, 'des' => 'ACACIAS', 'coddep' => '21'],
            ['cod' => 739, 'des' => 'BARRANCA DE UPIA', 'coddep' => '21'],
            ['cod' => 740, 'des' => 'CABUYARO', 'coddep' => '21'],
            ['cod' => 741, 'des' => 'CASTILLA LA NUEVA', 'coddep' => '21'],
            ['cod' => 742, 'des' => 'CUBARRAL', 'coddep' => '21'],
            ['cod' => 743, 'des' => 'CUMARAL', 'coddep' => '21'],
            ['cod' => 744, 'des' => 'EL CALVARIO', 'coddep' => '21'],
            ['cod' => 745, 'des' => 'EL CASTILLO', 'coddep' => '21'],
            ['cod' => 746, 'des' => 'EL DORADO', 'coddep' => '21'],
            ['cod' => 747, 'des' => 'FUENTE DE ORO', 'coddep' => '21'],
            ['cod' => 748, 'des' => 'GRANADA', 'coddep' => '21'],
            ['cod' => 749, 'des' => 'GUAMAL', 'coddep' => '21'],
            ['cod' => 750, 'des' => 'LA MACARENA', 'coddep' => '21'],
            ['cod' => 751, 'des' => 'LEJANIAS', 'coddep' => '21'],
            ['cod' => 752, 'des' => 'MAPIRIPAN', 'coddep' => '21'],
            ['cod' => 753, 'des' => 'MESETAS', 'coddep' => '21'],
            ['cod' => 754, 'des' => 'PUERTO CONCORDIA', 'coddep' => '21'],
            ['cod' => 755, 'des' => 'PUERTO GAITAN', 'coddep' => '21'],
            ['cod' => 756, 'des' => 'PUERTO LLERAS', 'coddep' => '21'],
            ['cod' => 757, 'des' => 'PUERTO LOPEZ', 'coddep' => '21'],
            ['cod' => 758, 'des' => 'PUERTO RICO', 'coddep' => '21'],
            ['cod' => 759, 'des' => 'RESTREPO', 'coddep' => '21'],
            ['cod' => 760, 'des' => 'SAN CARLOS DE GUAROA', 'coddep' => '21'],
            ['cod' => 761, 'des' => 'SAN JUAN DE ARAMA', 'coddep' => '21'],
            ['cod' => 762, 'des' => 'SAN JUANITO', 'coddep' => '21'],
            ['cod' => 763, 'des' => 'SAN MARTIN', 'coddep' => '21'],
            ['cod' => 764, 'des' => 'URIBE', 'coddep' => '21'],
            ['cod' => 765, 'des' => 'VILLAVICENCIO', 'coddep' => '21'],
            ['cod' => 766, 'des' => 'VISTAHERMOSA', 'coddep' => '21'],
            ['cod' => 767, 'des' => 'ALBAN', 'coddep' => '22'],
            ['cod' => 768, 'des' => 'ALDANA', 'coddep' => '22'],
            ['cod' => 769, 'des' => 'ANCUYA', 'coddep' => '22'],
            ['cod' => 770, 'des' => 'ARBOLEDA', 'coddep' => '22'],
            ['cod' => 771, 'des' => 'BARBACOAS', 'coddep' => '22'],
            ['cod' => 772, 'des' => 'BELEN', 'coddep' => '22'],
            ['cod' => 773, 'des' => 'BUESACO', 'coddep' => '22'],
            ['cod' => 774, 'des' => 'CHACHAGÜI', 'coddep' => '22'],
            ['cod' => 775, 'des' => 'COLON', 'coddep' => '22'],
            ['cod' => 776, 'des' => 'CONSACA', 'coddep' => '22'],
            ['cod' => 777, 'des' => 'CONTADERO', 'coddep' => '22'],
            ['cod' => 778, 'des' => 'CORDOBA', 'coddep' => '22'],
            ['cod' => 779, 'des' => 'CUASPUD', 'coddep' => '22'],
            ['cod' => 780, 'des' => 'CUMBAL', 'coddep' => '22'],
            ['cod' => 781, 'des' => 'CUMBITARA', 'coddep' => '22'],
            ['cod' => 782, 'des' => 'EL CHARCO', 'coddep' => '22'],
            ['cod' => 783, 'des' => 'EL PEÑOL', 'coddep' => '22'],
            ['cod' => 784, 'des' => 'EL ROSARIO', 'coddep' => '22'],
            ['cod' => 785, 'des' => 'EL TABLON DE GOMEZ', 'coddep' => '22'],
            ['cod' => 786, 'des' => 'EL TAMBO', 'coddep' => '22'],
            ['cod' => 787, 'des' => 'FRANCISCO PIZARRO', 'coddep' => '22'],
            ['cod' => 788, 'des' => 'FUNES', 'coddep' => '22'],
            ['cod' => 789, 'des' => 'GUACHUCAL', 'coddep' => '22'],
            ['cod' => 790, 'des' => 'GUAITARILLA', 'coddep' => '22'],
            ['cod' => 791, 'des' => 'GUALMATAN', 'coddep' => '22'],
            ['cod' => 792, 'des' => 'ILES', 'coddep' => '22'],
            ['cod' => 793, 'des' => 'IMUES', 'coddep' => '22'],
            ['cod' => 794, 'des' => 'IPIALES', 'coddep' => '22'],
            ['cod' => 795, 'des' => 'LA CRUZ', 'coddep' => '22'],
            ['cod' => 796, 'des' => 'LA FLORIDA', 'coddep' => '22'],
            ['cod' => 797, 'des' => 'LA LLANADA', 'coddep' => '22'],
            ['cod' => 798, 'des' => 'LA TOLA', 'coddep' => '22'],
            ['cod' => 799, 'des' => 'LA UNION', 'coddep' => '22'],
            ['cod' => 800, 'des' => 'LEIVA', 'coddep' => '22'],
            ['cod' => 801, 'des' => 'LINARES', 'coddep' => '22'],
            ['cod' => 802, 'des' => 'LOS ANDES', 'coddep' => '22'],
            ['cod' => 803, 'des' => 'MAGÜI', 'coddep' => '22'],
            ['cod' => 804, 'des' => 'MALLAMA', 'coddep' => '22'],
            ['cod' => 805, 'des' => 'MOSQUERA', 'coddep' => '22'],
            ['cod' => 806, 'des' => 'NARIÑO', 'coddep' => '22'],
            ['cod' => 807, 'des' => 'OLAYA HERRERA', 'coddep' => '22'],
            ['cod' => 808, 'des' => 'OSPINA', 'coddep' => '22'],
            ['cod' => 809, 'des' => 'PASTO', 'coddep' => '22'],
            ['cod' => 810, 'des' => 'POLICARPA', 'coddep' => '22'],
            ['cod' => 811, 'des' => 'POTOSI', 'coddep' => '22'],
            ['cod' => 812, 'des' => 'PROVIDENCIA', 'coddep' => '22'],
            ['cod' => 813, 'des' => 'PUERRES', 'coddep' => '22'],
            ['cod' => 814, 'des' => 'PUPIALES', 'coddep' => '22'],
            ['cod' => 815, 'des' => 'RICAURTE', 'coddep' => '22'],
            ['cod' => 816, 'des' => 'ROBERTO PAYAN', 'coddep' => '22'],
            ['cod' => 817, 'des' => 'SAMANIEGO', 'coddep' => '22'],
            ['cod' => 818, 'des' => 'SAN ANDRES DE TUMACO', 'coddep' => '22'],
            ['cod' => 819, 'des' => 'SAN BERNARDO', 'coddep' => '22'],
            ['cod' => 820, 'des' => 'SAN LORENZO', 'coddep' => '22'],
            ['cod' => 821, 'des' => 'SAN PABLO', 'coddep' => '22'],
            ['cod' => 822, 'des' => 'SAN PEDRO DE CARTAGO', 'coddep' => '22'],
            ['cod' => 823, 'des' => 'SANDONA', 'coddep' => '22'],
            ['cod' => 824, 'des' => 'SANTA BARBARA', 'coddep' => '22'],
            ['cod' => 825, 'des' => 'SANTACRUZ', 'coddep' => '22'],
            ['cod' => 826, 'des' => 'SAPUYES', 'coddep' => '22'],
            ['cod' => 827, 'des' => 'TAMINANGO', 'coddep' => '22'],
            ['cod' => 828, 'des' => 'TANGUA', 'coddep' => '22'],
            ['cod' => 829, 'des' => 'TUQUERRES', 'coddep' => '22'],
            ['cod' => 830, 'des' => 'YACUANQUER', 'coddep' => '22'],
            ['cod' => 831, 'des' => 'ABREGO', 'coddep' => '23'],
            ['cod' => 832, 'des' => 'ARBOLEDAS', 'coddep' => '23'],
            ['cod' => 833, 'des' => 'BOCHALEMA', 'coddep' => '23'],
            ['cod' => 834, 'des' => 'BUCARASICA', 'coddep' => '23'],
            ['cod' => 835, 'des' => 'CACHIRA', 'coddep' => '23'],
            ['cod' => 836, 'des' => 'CACOTA', 'coddep' => '23'],
            ['cod' => 837, 'des' => 'CHINACOTA', 'coddep' => '23'],
            ['cod' => 838, 'des' => 'CHITAGA', 'coddep' => '23'],
            ['cod' => 839, 'des' => 'CONVENCION', 'coddep' => '23'],
            ['cod' => 840, 'des' => 'CUCUTA', 'coddep' => '23'],
            ['cod' => 841, 'des' => 'CUCUTILLA', 'coddep' => '23'],
            ['cod' => 842, 'des' => 'DURANIA', 'coddep' => '23'],
            ['cod' => 843, 'des' => 'EL CARMEN', 'coddep' => '23'],
            ['cod' => 844, 'des' => 'EL TARRA', 'coddep' => '23'],
            ['cod' => 845, 'des' => 'EL ZULIA', 'coddep' => '23'],
            ['cod' => 846, 'des' => 'GRAMALOTE', 'coddep' => '23'],
            ['cod' => 847, 'des' => 'HACARI', 'coddep' => '23'],
            ['cod' => 848, 'des' => 'HERRAN', 'coddep' => '23'],
            ['cod' => 849, 'des' => 'LA ESPERANZA', 'coddep' => '23'],
            ['cod' => 850, 'des' => 'LA PLAYA', 'coddep' => '23'],
            ['cod' => 851, 'des' => 'LABATECA', 'coddep' => '23'],
            ['cod' => 852, 'des' => 'LOS PATIOS', 'coddep' => '23'],
            ['cod' => 853, 'des' => 'LOURDES', 'coddep' => '23'],
            ['cod' => 854, 'des' => 'MUTISCUA', 'coddep' => '23'],
            ['cod' => 855, 'des' => 'OCAÑA', 'coddep' => '23'],
            ['cod' => 856, 'des' => 'PAMPLONA', 'coddep' => '23'],
            ['cod' => 857, 'des' => 'PAMPLONITA', 'coddep' => '23'],
            ['cod' => 858, 'des' => 'PUERTO SANTANDER', 'coddep' => '23'],
            ['cod' => 859, 'des' => 'RAGONVALIA', 'coddep' => '23'],
            ['cod' => 860, 'des' => 'SALAZAR', 'coddep' => '23'],
            ['cod' => 861, 'des' => 'SAN CALIXTO', 'coddep' => '23'],
            ['cod' => 862, 'des' => 'SAN CAYETANO', 'coddep' => '23'],
            ['cod' => 863, 'des' => 'SANTIAGO', 'coddep' => '23'],
            ['cod' => 864, 'des' => 'SARDINATA', 'coddep' => '23'],
            ['cod' => 865, 'des' => 'SILOS', 'coddep' => '23'],
            ['cod' => 866, 'des' => 'TEORAMA', 'coddep' => '23'],
            ['cod' => 867, 'des' => 'TIBU', 'coddep' => '23'],
            ['cod' => 868, 'des' => 'TOLEDO', 'coddep' => '23'],
            ['cod' => 869, 'des' => 'VILLA CARO', 'coddep' => '23'],
            ['cod' => 870, 'des' => 'VILLA DEL ROSARIO', 'coddep' => '23'],
            ['cod' => 871, 'des' => 'COLON', 'coddep' => '24'],
            ['cod' => 872, 'des' => 'MOCOA', 'coddep' => '24'],
            ['cod' => 873, 'des' => 'ORITO', 'coddep' => '24'],
            ['cod' => 874, 'des' => 'PUERTO ASIS', 'coddep' => '24'],
            ['cod' => 875, 'des' => 'PUERTO CAICEDO', 'coddep' => '24'],
            ['cod' => 876, 'des' => 'PUERTO GUZMAN', 'coddep' => '24'],
            ['cod' => 877, 'des' => 'PUERTO LEGUIZAMO', 'coddep' => '24'],
            ['cod' => 878, 'des' => 'SAN FRANCISCO', 'coddep' => '24'],
            ['cod' => 879, 'des' => 'SAN MIGUEL', 'coddep' => '24'],
            ['cod' => 880, 'des' => 'SANTIAGO', 'coddep' => '24'],
            ['cod' => 881, 'des' => 'SIBUNDOY', 'coddep' => '24'],
            ['cod' => 882, 'des' => 'VALLE DEL GUAMUEZ', 'coddep' => '24'],
            ['cod' => 883, 'des' => 'VILLAGARZON', 'coddep' => '24'],
            ['cod' => 884, 'des' => 'ARMENIA', 'coddep' => '25'],
            ['cod' => 885, 'des' => 'BUENAVISTA', 'coddep' => '25'],
            ['cod' => 886, 'des' => 'CALARCA', 'coddep' => '25'],
            ['cod' => 887, 'des' => 'CIRCASIA', 'coddep' => '25'],
            ['cod' => 888, 'des' => 'CORDOBA', 'coddep' => '25'],
            ['cod' => 889, 'des' => 'FILANDIA', 'coddep' => '25'],
            ['cod' => 890, 'des' => 'GENOVA', 'coddep' => '25'],
            ['cod' => 891, 'des' => 'LA TEBAIDA', 'coddep' => '25'],
            ['cod' => 892, 'des' => 'MONTENEGRO', 'coddep' => '25'],
            ['cod' => 893, 'des' => 'PIJAO', 'coddep' => '25'],
            ['cod' => 894, 'des' => 'QUIMBAYA', 'coddep' => '25'],
            ['cod' => 895, 'des' => 'SALENTO', 'coddep' => '25'],
            ['cod' => 896, 'des' => 'APIA', 'coddep' => '26'],
            ['cod' => 897, 'des' => 'BALBOA', 'coddep' => '26'],
            ['cod' => 898, 'des' => 'BELEN DE UMBRIA', 'coddep' => '26'],
            ['cod' => 899, 'des' => 'DOSQUEBRADAS', 'coddep' => '26'],
            ['cod' => 900, 'des' => 'GUATICA', 'coddep' => '26'],
            ['cod' => 901, 'des' => 'LA CELIA', 'coddep' => '26'],
            ['cod' => 902, 'des' => 'LA VIRGINIA', 'coddep' => '26'],
            ['cod' => 903, 'des' => 'MARSELLA', 'coddep' => '26'],
            ['cod' => 904, 'des' => 'MISTRATO', 'coddep' => '26'],
            ['cod' => 905, 'des' => 'PEREIRA', 'coddep' => '26'],
            ['cod' => 906, 'des' => 'PUEBLO RICO', 'coddep' => '26'],
            ['cod' => 907, 'des' => 'QUINCHIA', 'coddep' => '26'],
            ['cod' => 908, 'des' => 'SANTA ROSA DE CABAL', 'coddep' => '26'],
            ['cod' => 909, 'des' => 'SANTUARIO', 'coddep' => '26'],
            ['cod' => 910, 'des' => 'PROVIDENCIA', 'coddep' => '27'],
            ['cod' => 911, 'des' => 'SAN ANDRES', 'coddep' => '27'],
            ['cod' => 912, 'des' => 'AGUADA', 'coddep' => '28'],
            ['cod' => 913, 'des' => 'ALBANIA', 'coddep' => '28'],
            ['cod' => 914, 'des' => 'ARATOCA', 'coddep' => '28'],
            ['cod' => 915, 'des' => 'BARBOSA', 'coddep' => '28'],
            ['cod' => 916, 'des' => 'BARICHARA', 'coddep' => '28'],
            ['cod' => 917, 'des' => 'BARRANCABERMEJA', 'coddep' => '28'],
            ['cod' => 918, 'des' => 'BETULIA', 'coddep' => '28'],
            ['cod' => 919, 'des' => 'BOLIVAR', 'coddep' => '28'],
            ['cod' => 920, 'des' => 'BUCARAMANGA', 'coddep' => '28'],
            ['cod' => 921, 'des' => 'CABRERA', 'coddep' => '28'],
            ['cod' => 922, 'des' => 'CALIFORNIA', 'coddep' => '28'],
            ['cod' => 923, 'des' => 'CAPITANEJO', 'coddep' => '28'],
            ['cod' => 924, 'des' => 'CARCASI', 'coddep' => '28'],
            ['cod' => 925, 'des' => 'CEPITA', 'coddep' => '28'],
            ['cod' => 926, 'des' => 'CERRITO', 'coddep' => '28'],
            ['cod' => 927, 'des' => 'CHARALA', 'coddep' => '28'],
            ['cod' => 928, 'des' => 'CHARTA', 'coddep' => '28'],
            ['cod' => 929, 'des' => 'CHIMA', 'coddep' => '28'],
            ['cod' => 930, 'des' => 'CHIPATA', 'coddep' => '28'],
            ['cod' => 931, 'des' => 'CIMITARRA', 'coddep' => '28'],
            ['cod' => 932, 'des' => 'CONCEPCION', 'coddep' => '28'],
            ['cod' => 933, 'des' => 'CONFINES', 'coddep' => '28'],
            ['cod' => 934, 'des' => 'CONTRATACION', 'coddep' => '28'],
            ['cod' => 935, 'des' => 'COROMORO', 'coddep' => '28'],
            ['cod' => 936, 'des' => 'CURITI', 'coddep' => '28'],
            ['cod' => 937, 'des' => 'EL CARMEN DE CHUCURI', 'coddep' => '28'],
            ['cod' => 938, 'des' => 'EL GUACAMAYO', 'coddep' => '28'],
            ['cod' => 939, 'des' => 'EL PEÑON', 'coddep' => '28'],
            ['cod' => 940, 'des' => 'EL PLAYON', 'coddep' => '28'],
            ['cod' => 941, 'des' => 'ENCINO', 'coddep' => '28'],
            ['cod' => 942, 'des' => 'ENCISO', 'coddep' => '28'],
            ['cod' => 943, 'des' => 'FLORIAN', 'coddep' => '28'],
            ['cod' => 944, 'des' => 'FLORIDABLANCA', 'coddep' => '28'],
            ['cod' => 945, 'des' => 'GALAN', 'coddep' => '28'],
            ['cod' => 946, 'des' => 'GAMBITA', 'coddep' => '28'],
            ['cod' => 947, 'des' => 'GIRON', 'coddep' => '28'],
            ['cod' => 948, 'des' => 'GUACA', 'coddep' => '28'],
            ['cod' => 949, 'des' => 'GUADALUPE', 'coddep' => '28'],
            ['cod' => 950, 'des' => 'GUAPOTA', 'coddep' => '28'],
            ['cod' => 951, 'des' => 'GUAVATA', 'coddep' => '28'],
            ['cod' => 952, 'des' => 'GÜEPSA', 'coddep' => '28'],
            ['cod' => 953, 'des' => 'HATO', 'coddep' => '28'],
            ['cod' => 954, 'des' => 'JESUS MARIA', 'coddep' => '28'],
            ['cod' => 955, 'des' => 'JORDAN', 'coddep' => '28'],
            ['cod' => 956, 'des' => 'LA BELLEZA', 'coddep' => '28'],
            ['cod' => 957, 'des' => 'LA PAZ', 'coddep' => '28'],
            ['cod' => 958, 'des' => 'LANDAZURI', 'coddep' => '28'],
            ['cod' => 959, 'des' => 'LEBRIJA', 'coddep' => '28'],
            ['cod' => 960, 'des' => 'LOS SANTOS', 'coddep' => '28'],
            ['cod' => 961, 'des' => 'MACARAVITA', 'coddep' => '28'],
            ['cod' => 962, 'des' => 'MALAGA', 'coddep' => '28'],
            ['cod' => 963, 'des' => 'MATANZA', 'coddep' => '28'],
            ['cod' => 964, 'des' => 'MOGOTES', 'coddep' => '28'],
            ['cod' => 965, 'des' => 'MOLAGAVITA', 'coddep' => '28'],
            ['cod' => 966, 'des' => 'OCAMONTE', 'coddep' => '28'],
            ['cod' => 967, 'des' => 'OIBA', 'coddep' => '28'],
            ['cod' => 968, 'des' => 'ONZAGA', 'coddep' => '28'],
            ['cod' => 969, 'des' => 'PALMAR', 'coddep' => '28'],
            ['cod' => 970, 'des' => 'PALMAS DEL SOCORRO', 'coddep' => '28'],
            ['cod' => 971, 'des' => 'PARAMO', 'coddep' => '28'],
            ['cod' => 972, 'des' => 'PIEDECUESTA', 'coddep' => '28'],
            ['cod' => 973, 'des' => 'PINCHOTE', 'coddep' => '28'],
            ['cod' => 974, 'des' => 'PUENTE NACIONAL', 'coddep' => '28'],
            ['cod' => 975, 'des' => 'PUERTO PARRA', 'coddep' => '28'],
            ['cod' => 976, 'des' => 'PUERTO WILCHES', 'coddep' => '28'],
            ['cod' => 977, 'des' => 'RIONEGRO', 'coddep' => '28'],
            ['cod' => 978, 'des' => 'SABANA DE TORRES', 'coddep' => '28'],
            ['cod' => 979, 'des' => 'SAN ANDRES', 'coddep' => '28'],
            ['cod' => 980, 'des' => 'SAN BENITO', 'coddep' => '28'],
            ['cod' => 981, 'des' => 'SAN GIL', 'coddep' => '28'],
            ['cod' => 982, 'des' => 'SAN JOAQUIN', 'coddep' => '28'],
            ['cod' => 983, 'des' => 'SAN JOSE DE MIRANDA', 'coddep' => '28'],
            ['cod' => 984, 'des' => 'SAN MIGUEL', 'coddep' => '28'],
            ['cod' => 985, 'des' => 'SAN VICENTE DE CHUCURI', 'coddep' => '28'],
            ['cod' => 986, 'des' => 'SANTA BARBARA', 'coddep' => '28'],
            ['cod' => 987, 'des' => 'SANTA HELENA DEL OPON', 'coddep' => '28'],
            ['cod' => 988, 'des' => 'SIMACOTA', 'coddep' => '28'],
            ['cod' => 989, 'des' => 'SOCORRO', 'coddep' => '28'],
            ['cod' => 990, 'des' => 'SUAITA', 'coddep' => '28'],
            ['cod' => 991, 'des' => 'SUCRE', 'coddep' => '28'],
            ['cod' => 992, 'des' => 'SURATA', 'coddep' => '28'],
            ['cod' => 993, 'des' => 'TONA', 'coddep' => '28'],
            ['cod' => 994, 'des' => 'VALLE DE SAN JOSE', 'coddep' => '28'],
            ['cod' => 995, 'des' => 'VELEZ', 'coddep' => '28'],
            ['cod' => 996, 'des' => 'VETAS', 'coddep' => '28'],
            ['cod' => 997, 'des' => 'VILLANUEVA', 'coddep' => '28'],
            ['cod' => 998, 'des' => 'ZAPATOCA', 'coddep' => '28'],
            ['cod' => 999, 'des' => 'BUENAVISTA', 'coddep' => '29'],
            ['cod' => 1000, 'des' => 'CAIMITO', 'coddep' => '29'],
            ['cod' => 1001, 'des' => 'CHALAN', 'coddep' => '29'],
            ['cod' => 1002, 'des' => 'COLOSO', 'coddep' => '29'],
            ['cod' => 1003, 'des' => 'COROZAL', 'coddep' => '29'],
            ['cod' => 1004, 'des' => 'COVEÑAS', 'coddep' => '29'],
            ['cod' => 1005, 'des' => 'EL ROBLE', 'coddep' => '29'],
            ['cod' => 1006, 'des' => 'GALERAS', 'coddep' => '29'],
            ['cod' => 1007, 'des' => 'GUARANDA', 'coddep' => '29'],
            ['cod' => 1008, 'des' => 'LA UNION', 'coddep' => '29'],
            ['cod' => 1009, 'des' => 'LOS PALMITOS', 'coddep' => '29'],
            ['cod' => 1010, 'des' => 'MAJAGUAL', 'coddep' => '29'],
            ['cod' => 1011, 'des' => 'MORROA', 'coddep' => '29'],
            ['cod' => 1012, 'des' => 'OVEJAS', 'coddep' => '29'],
            ['cod' => 1013, 'des' => 'PALMITO', 'coddep' => '29'],
            ['cod' => 1014, 'des' => 'SAMPUES', 'coddep' => '29'],
            ['cod' => 1015, 'des' => 'SAN BENITO ABAD', 'coddep' => '29'],
            ['cod' => 1016, 'des' => 'SAN JUAN DE BETULIA', 'coddep' => '29'],
            ['cod' => 1017, 'des' => 'SAN LUIS DE SINCE', 'coddep' => '29'],
            ['cod' => 1018, 'des' => 'SAN MARCOS', 'coddep' => '29'],
            ['cod' => 1019, 'des' => 'SAN ONOFRE', 'coddep' => '29'],
            ['cod' => 1020, 'des' => 'SAN PEDRO', 'coddep' => '29'],
            ['cod' => 1021, 'des' => 'SANTIAGO DE TOLU', 'coddep' => '29'],
            ['cod' => 1022, 'des' => 'SINCELEJO', 'coddep' => '29'],
            ['cod' => 1023, 'des' => 'SUCRE', 'coddep' => '29'],
            ['cod' => 1024, 'des' => 'TOLU VIEJO', 'coddep' => '29'],
            ['cod' => 1025, 'des' => 'ALPUJARRA', 'coddep' => '30'],
            ['cod' => 1026, 'des' => 'ALVARADO', 'coddep' => '30'],
            ['cod' => 1027, 'des' => 'AMBALEMA', 'coddep' => '30'],
            ['cod' => 1028, 'des' => 'ANZOATEGUI', 'coddep' => '30'],
            ['cod' => 1029, 'des' => 'ARMERO', 'coddep' => '30'],
            ['cod' => 1030, 'des' => 'ATACO', 'coddep' => '30'],
            ['cod' => 1031, 'des' => 'CAJAMARCA', 'coddep' => '30'],
            ['cod' => 1032, 'des' => 'CARMEN DE APICALA', 'coddep' => '30'],
            ['cod' => 1033, 'des' => 'CASABIANCA', 'coddep' => '30'],
            ['cod' => 1034, 'des' => 'CHAPARRAL', 'coddep' => '30'],
            ['cod' => 1035, 'des' => 'COELLO', 'coddep' => '30'],
            ['cod' => 1036, 'des' => 'COYAIMA', 'coddep' => '30'],
            ['cod' => 1037, 'des' => 'CUNDAY', 'coddep' => '30'],
            ['cod' => 1038, 'des' => 'DOLORES', 'coddep' => '30'],
            ['cod' => 1039, 'des' => 'ESPINAL', 'coddep' => '30'],
            ['cod' => 1040, 'des' => 'FALAN', 'coddep' => '30'],
            ['cod' => 1041, 'des' => 'FLANDES', 'coddep' => '30'],
            ['cod' => 1042, 'des' => 'FRESNO', 'coddep' => '30'],
            ['cod' => 1043, 'des' => 'GUAMO', 'coddep' => '30'],
            ['cod' => 1044, 'des' => 'HERVEO', 'coddep' => '30'],
            ['cod' => 1045, 'des' => 'HONDA', 'coddep' => '30'],
            ['cod' => 1046, 'des' => 'IBAGUE', 'coddep' => '30'],
            ['cod' => 1047, 'des' => 'ICONONZO', 'coddep' => '30'],
            ['cod' => 1048, 'des' => 'LERIDA', 'coddep' => '30'],
            ['cod' => 1049, 'des' => 'LIBANO', 'coddep' => '30'],
            ['cod' => 1050, 'des' => 'MELGAR', 'coddep' => '30'],
            ['cod' => 1051, 'des' => 'MURILLO', 'coddep' => '30'],
            ['cod' => 1052, 'des' => 'NATAGAIMA', 'coddep' => '30'],
            ['cod' => 1053, 'des' => 'ORTEGA', 'coddep' => '30'],
            ['cod' => 1054, 'des' => 'PALOCABILDO', 'coddep' => '30'],
            ['cod' => 1055, 'des' => 'PIEDRAS', 'coddep' => '30'],
            ['cod' => 1056, 'des' => 'PLANADAS', 'coddep' => '30'],
            ['cod' => 1057, 'des' => 'PRADO', 'coddep' => '30'],
            ['cod' => 1058, 'des' => 'PURIFICACION', 'coddep' => '30'],
            ['cod' => 1059, 'des' => 'RIOBLANCO', 'coddep' => '30'],
            ['cod' => 1060, 'des' => 'RONCESVALLES', 'coddep' => '30'],
            ['cod' => 1061, 'des' => 'ROVIRA', 'coddep' => '30'],
            ['cod' => 1062, 'des' => 'SALDAÑA', 'coddep' => '30'],
            ['cod' => 1063, 'des' => 'SAN ANTONIO', 'coddep' => '30'],
            ['cod' => 1064, 'des' => 'SAN LUIS', 'coddep' => '30'],
            ['cod' => 1065, 'des' => 'SAN SEBASTIAN DE MARIQUITA', 'coddep' => '30'],
            ['cod' => 1066, 'des' => 'SANTA ISABEL', 'coddep' => '30'],
            ['cod' => 1067, 'des' => 'SUAREZ', 'coddep' => '30'],
            ['cod' => 1068, 'des' => 'VALLE DE SAN JUAN', 'coddep' => '30'],
            ['cod' => 1069, 'des' => 'VENADILLO', 'coddep' => '30'],
            ['cod' => 1070, 'des' => 'VILLAHERMOSA', 'coddep' => '30'],
            ['cod' => 1071, 'des' => 'VILLARRICA', 'coddep' => '30'],
            ['cod' => 1072, 'des' => 'ALCALA', 'coddep' => '31'],
            ['cod' => 1073, 'des' => 'ANDALUCIA', 'coddep' => '31'],
            ['cod' => 1074, 'des' => 'ANSERMANUEVO', 'coddep' => '31'],
            ['cod' => 1075, 'des' => 'ARGELIA', 'coddep' => '31'],
            ['cod' => 1076, 'des' => 'BOLIVAR', 'coddep' => '31'],
            ['cod' => 1077, 'des' => 'BUENAVENTURA', 'coddep' => '31'],
            ['cod' => 1078, 'des' => 'BUGALAGRANDE', 'coddep' => '31'],
            ['cod' => 1079, 'des' => 'CAICEDONIA', 'coddep' => '31'],
            ['cod' => 1080, 'des' => 'CALI', 'coddep' => '31'],
            ['cod' => 1081, 'des' => 'CALIMA', 'coddep' => '31'],
            ['cod' => 1082, 'des' => 'CANDELARIA', 'coddep' => '31'],
            ['cod' => 1083, 'des' => 'CARTAGO', 'coddep' => '31'],
            ['cod' => 1084, 'des' => 'DAGUA', 'coddep' => '31'],
            ['cod' => 1085, 'des' => 'EL AGUILA', 'coddep' => '31'],
            ['cod' => 1086, 'des' => 'EL CAIRO', 'coddep' => '31'],
            ['cod' => 1087, 'des' => 'EL CERRITO', 'coddep' => '31'],
            ['cod' => 1088, 'des' => 'EL DOVIO', 'coddep' => '31'],
            ['cod' => 1089, 'des' => 'FLORIDA', 'coddep' => '31'],
            ['cod' => 1090, 'des' => 'GINEBRA', 'coddep' => '31'],
            ['cod' => 1091, 'des' => 'GUACARI', 'coddep' => '31'],
            ['cod' => 1092, 'des' => 'GUADALAJARA DE BUGA', 'coddep' => '31'],
            ['cod' => 1093, 'des' => 'JAMUNDI', 'coddep' => '31'],
            ['cod' => 1094, 'des' => 'LA CUMBRE', 'coddep' => '31'],
            ['cod' => 1095, 'des' => 'LA UNION', 'coddep' => '31'],
            ['cod' => 1096, 'des' => 'LA VICTORIA', 'coddep' => '31'],
            ['cod' => 1097, 'des' => 'OBANDO', 'coddep' => '31'],
            ['cod' => 1098, 'des' => 'PALMIRA', 'coddep' => '31'],
            ['cod' => 1099, 'des' => 'PRADERA', 'coddep' => '31'],
            ['cod' => 1100, 'des' => 'RESTREPO', 'coddep' => '31'],
            ['cod' => 1101, 'des' => 'RIOFRIO', 'coddep' => '31'],
            ['cod' => 1102, 'des' => 'ROLDANILLO', 'coddep' => '31'],
            ['cod' => 1103, 'des' => 'SAN PEDRO', 'coddep' => '31'],
            ['cod' => 1104, 'des' => 'SEVILLA', 'coddep' => '31'],
            ['cod' => 1105, 'des' => 'TORO', 'coddep' => '31'],
            ['cod' => 1106, 'des' => 'TRUJILLO', 'coddep' => '31'],
            ['cod' => 1107, 'des' => 'TULUA', 'coddep' => '31'],
            ['cod' => 1108, 'des' => 'ULLOA', 'coddep' => '31'],
            ['cod' => 1109, 'des' => 'VERSALLES', 'coddep' => '31'],
            ['cod' => 1110, 'des' => 'VIJES', 'coddep' => '31'],
            ['cod' => 1111, 'des' => 'YOTOCO', 'coddep' => '31'],
            ['cod' => 1112, 'des' => 'YUMBO', 'coddep' => '31'],
            ['cod' => 1113, 'des' => 'ZARZAL', 'coddep' => '31'],
            ['cod' => 1114, 'des' => 'CARURU', 'coddep' => '32'],
            ['cod' => 1115, 'des' => 'MITU', 'coddep' => '32'],
            ['cod' => 1116, 'des' => 'PACOA', 'coddep' => '32'],
            ['cod' => 1117, 'des' => 'PAPUNAUA', 'coddep' => '32'],
            ['cod' => 1118, 'des' => 'TARAIRA', 'coddep' => '32'],
            ['cod' => 1119, 'des' => 'YAVARATE', 'coddep' => '32'],
            ['cod' => 1120, 'des' => 'CUMARIBO', 'coddep' => '33'],
            ['cod' => 1121, 'des' => 'LA PRIMAVERA', 'coddep' => '33'],
            ['cod' => 1122, 'des' => 'PUERTO CARREÑO', 'coddep' => '33'],
            ['cod' => 1123, 'des' => 'SANTA ROSALIA', 'coddep' => '33'],
        ]);
    }
}